source "https://rubygems.org"

# Use the github-pages gem to match the exact versions GitHub Pages uses.
# See: https://pages.github.com/versions/
gem "github-pages", group: :jekyll_plugins

# Local Jekyll server extras
group :jekyll_plugins do
  gem "jekyll-livereload"
end
